spring.application.name=object-storage

management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=always

info.app.version=1.0.0
info.app.description=Mini Object Storage API

api.key=${API_KEY:secret-key}